---

# no default yaml module: https://github.com/kwoodson/yedit

- name: configure replication set
  blockinfile:
    dest: "{{ mongodb_conf }}"
    block: |
      replication:
        replSetName: caldera
    backup: yes
