---

- name: Download UPX
  ansible.builtin.get_url:
    url: "https://github.com/upx/upx/releases/download/v{{ caldera_upx_version }}/upx-{{ caldera_upx_version }}-amd64_linux.tar.xz"
    dest: "{{ caldera_home }}"
    mode: '0644'
    owner: root
    group: root

- name: Unarchive UPX
  ansible.builtin.unarchive:
    src: "{{ caldera_home }}/upx-{{ caldera_upx_version }}-amd64_linux.tar.xz"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
    owner: root
    group: root
    # include: not working with tar
    exclude:
      - COPYING
      - LICENSE
      - NEWS
      - README
      - THANKS.txt
      - upx-doc.html
      - upx-doc.txt
      - upx.1
    extra_opts: '--strip-components=1'
